ogr-decode --all-threads --max-segment 500 --area-type Urban work/Urban clc_urban                                                                                                                                                          
ogr-decode --all-threads --max-segment 500 --area-type Town work/Town clc_town                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Industrial work/Industrial clc_industrial                                                                                                                                                     
ogr-decode --all-threads --max-segment 500 --area-type Transport work/Transport clc_transport                                                                                                                                                      
ogr-decode --all-threads --max-segment 500 --area-type Port work/Port clc_port                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Airport work/Airport clc_airports                                                                                                                                                       
ogr-decode --all-threads --max-segment 500 --area-type OpenMining work/OpenMining clc_openmining                                                                                                                                                     
ogr-decode --all-threads --max-segment 500 --area-type Dump work/Dump clc_dump                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Construction work/Construction clc_construction                                                                                                                                                   
ogr-decode --all-threads --max-segment 500 --area-type Greenspace work/Greenspace clc_greenspace
ogr-decode --all-threads --max-segment 500 --area-type GolfCourse work/GolfCourse clc_leisure
ogr-decode --all-threads --max-segment 500 --area-type DryCrop work/DryCrop clc_drycrop
ogr-decode --all-threads --max-segment 500 --area-type IrrCrop work/IrrCrop clc_irrcrop
ogr-decode --all-threads --max-segment 500 --area-type Rice work/Rice clc_rice
ogr-decode --all-threads --max-segment 500 --area-type Vineyard work/Vineyard clc_vineyard
ogr-decode --all-threads --max-segment 500 --area-type Orchard work/Orchard clc_orchard
ogr-decode --all-threads --max-segment 500 --area-type Olives work/Olives clc_olives
ogr-decode --all-threads --max-segment 500 --area-type MixedCrop work/MixedCrop clc_pasture
ogr-decode --all-threads --max-segment 500 --area-type MixedCrop work/MixedCrop clc_mixedcrop
ogr-decode --all-threads --max-segment 500 --area-type ComplexCrop work/ComplexCrop clc_complexcrop
ogr-decode --all-threads --max-segment 500 --area-type NaturalCrop work/NaturalCrop clc_naturalcrop
ogr-decode --all-threads --max-segment 500 --area-type AgroForest work/AgroForest clc_agroforest
ogr-decode --all-threads --max-segment 500 --area-type DeciduousForest work/DeciduousForest clc_deciduousforest
ogr-decode --all-threads --max-segment 500 --area-type EvergreenForest work/EvergreenForest clc_evergreenforest
ogr-decode --all-threads --max-segment 500 --area-type MixedForest work/MixedForest clc_mixedforest
ogr-decode --all-threads --max-segment 500 --area-type Grassland work/Grassland clc_grassland
ogr-decode --all-threads --max-segment 500 --area-type Heath work/Heath clc_heath
ogr-decode --all-threads --max-segment 500 --area-type Sclerophyllous work/Sclerophyllous clc_sclerophyllous
ogr-decode --all-threads --max-segment 500 --area-type Scrub work/Scrub clc_scrub
ogr-decode --all-threads --max-segment 500 --area-type Sand work/Sand clc_sand
ogr-decode --all-threads --max-segment 500 --area-type Rock work/Rock clc_rock
ogr-decode --all-threads --max-segment 500 --area-type BarrenCover work/BarrenCover clc_barrencover
ogr-decode --all-threads --max-segment 500 --area-type Burnt work/Burnt clc_burnt
ogr-decode --all-threads --max-segment 500 --area-type Glacier work/Glacier clc_glacier
ogr-decode --all-threads --max-segment 500 --area-type Marsh work/Marsh clc_marsh
ogr-decode --all-threads --max-segment 500 --area-type Bog work/Bog clc_bog
ogr-decode --all-threads --max-segment 500 --area-type SaltMarsh work/SaltMarsh clc_saltmarsh
ogr-decode --all-threads --max-segment 500 --area-type Saline work/Saline clc_saline
ogr-decode --all-threads --max-segment 500 --area-type Intertidal work/Intertidal clc_intertidal
ogr-decode --all-threads --max-segment 500 --area-type Lake work/Lake clc_river
ogr-decode --all-threads --max-segment 500 --area-type Lake work/Lake clc_lake
ogr-decode --all-threads --max-segment 500 --area-type Lagoon work/Lagoon clc_lagoon
ogr-decode --all-threads --max-segment 500 --area-type Estuary work/Estuary clc_estuary

 
